### PR TITLE
change git clone depth to 1

### PR DESCRIPTION
**Pull request by ProfMerlin**

### CODE REVIEW

**Comment by jerith** [comment]
We need to either depend on older Twisted or kill the Python 2.6 builds. My vote is for the latter.

**Comment by jerith** [comment]
Also, what's the motivation for this change?

**Comment by ProfMerlin** [comment]
I have been told that clones can be up to 10 times laster (especially with telkom) since it does not need to clone the whole revision every time

**Comment by jerith** [comment]
Can we switch branches properly with a shallow clone?

**Pull request closed without merging**
